version: '3'

services:

  flight_service: # flight service
    container_name: flight_service
    hostname: flight_service
    command: 'sh -c ''pip install --upgrade pip && pip install -r requirements.txt &&  python flight_service.py'''
    image: python:3.7
    volumes:
      - '.:/app'
    depends_on:
      - flight_db
    restart: always

  flight_db: # flight db
    hostname: flight_db
    container_name: flight_db
    image: mongo:4.4
    command: mongod --port 27018
    volumes:
      - ./mongodb/data1/db:/data/db
      - ./mongodb/data1/configdb:/data/configdb
    expose:
      - 27018
    ports:
      - 27018:27018
    restart: always


networks:
  default:
    external:
      name: rabbitmq_network_orc