version: '3'

services:

  payment_service: # payment_service
    container_name: payment_service
    hostname: payment_service
    command: 'sh -c ''pip install --upgrade pip && pip install -r requirements.txt &&  python flight_service.py'''
    image: python:3.7
    volumes:
      - '.:/app'
    depends_on:
      - payment_db

    restart: always

  payment_db: # payment db
    hostname: payment_db
    container_name: payment_db
    image: mongo:4.4
    command: mongod --port 27019
    volumes:
      - ./mongodb/data1/db:/data/db
      - ./mongodb/data1/configdb:/data/configdb
    expose:
      - 27019
    ports:
      - 27019:27019
    restart: always




networks:
  default:
    external:
      name: rabbitmq_network_orc